# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lsgames-frontend
  labels:
    app: lsgames-frontend
  namespace: smkz-for-work
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lsgames-frontend
  template:
    metadata:
      labels:
        app: lsgames-frontend
    spec:
      containers:
        - name: lsgames-frontend
          image: $secrets.REGISTRY_URL/lsgames-frontend:latest
          resources:
            requests:
              memory: 512Mi
              cpu: 250m
            limits:
              memory: 512Mi
              cpu: 250m
          ports:
            - containerPort: 80
              protocol: TCP

---
# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: lsgames-frontend
  namespace: smkz-for-work
spec:
  type: ClusterIP
  selector:
    app: lsgames-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
